export const MENU_ITEM_PARENT = {
    DASHBOARD: "Dashboard",
    WALLET_BALANCE: "Wallet Balance",
    CONTRIBUTIONS: "Contributions",
    LOANS: "Loans",
    PAYMENTS: "Payments",
    RECEIPTS: "Receipts",
    MEMBERS: "Members",
    GOALS: "Goals",
    VIOLATIONS: "Violations",
    REPORTS: "Reports",
    SETTINGS: "Settings",
};
export const MENU_ITEM_CHILDREN = {
    VIEW_CONTRIBUTIONS: "View Contributions",
    ADD_CONTRIBUTIONS: "Add Contributions",
    HISTORY_CONTRIBUTIONS: "Contribution History",
    VIEW_LOAN: "View Loans",
    REQUEST_LOAN: "Request Loan",
    HISTORY_LOAN: "Loan History",
    VIEW_PAYMENTS: "View Payments",
    PROOF_OF_PAYMETS: "Proof of Payments",
    HISTORY_PAYMENTS: "Payments History",
    MEMBER_RECEIPT: "Member's Receipt",
    TREASURER_RECEIPT: "Treasurer's Receipt",
    VIEW_MEMBERS: "View Members",
    EQUILIZER: "Equilizer",
    SET_GOALS: "Set Goals",
    TRACK_GOALS: "Track Goals",
    VIEW_VIOLATIONS: "View Violations",
    REPORT_VIOLATION: "Report Violation",
    SUMMARY: "Summary",
    GENERATE_REPORT: "Generate Report",
    EXPORT_REPORT: "Export Report",
    PROFILE_SETTINGS: "Profile Settings",
    PRIVACY_SETTINGS: "Privacy Settings",
};